### ISSUE TITLE
Server crash on connect since latest cs2 update

### ISSUE THREAD

**Issue by asdfxD** [KillStr3aK/IgnoreMessages#1]
my server crashes on player connect with only this plugin enabled in cssharp

edit: it does not crash when cs2fixes is disabled, but it crashes with cs2fixes enabled

maybe there is a conflict with both cs2fixes and IgnoreMessages, cause when i have both installed:

[CS2Fixes] **Failed to find address** for UTIL_ClientPrintAll
Listing 2 plugins:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
  [02] FAILED

when i remove IgnoreMessages:

[CS2Fixes] **Found** UTIL_ClientPrintAll at 0x0x7f6c0abd7a00
Listing 2 plugins:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
  [02] CS2Fixes (1.1) by xen, Poggu, and the Source2ZE community

**Comment by KillStr3aK** [comment]
as of cssharp has no compat support with cs2fixes (yet) nor this plugin has
